# Permutations and combinations

A *permutation* of a list of objects is an arrangement or rearrangement of its members into a sequence. The word *permutation* also refers to the process of changing the  order of the set.


The number of permutations of a sequence of 3 objects (e.g. three colors [red, blue, green]) are all the possible orderings of this three-element set, which are 6:

[red, blue, green]

[red, green, blue]

[green, red, blue]

[green, blue, red]

[blue, red, green]

[blue, green, red]

The number of permutations of n distinct objects is  *n!* (*n factorial*) which means the product of all positive integers less than or equal to n:

$n! = n (n-1) (n-2) ... (3) (2) (1) $

In fact, there are $n$ ways to choose the object that occupies the first position, for each of them there are $n-1$ ways to choose the object that occupies the second position, then for each pair of objects fixed in the first two positions there are $n-2$ ways to choose the object in the third position, and so on, until all positions are filled.




*Permutations* differ from *combinations*, which are selections of some members of a set regardless of order.  A combination is a selection of items from a collection, such that the order of selection does not matter.

A $k$-combination of a set $S$ is a subset of $k$ distinct elements of $S$. If the set has $n$ elements, the number of $k$-combinations is equal to the *binomial coefficient*:

$\binom{n}{k} = \frac{n!}{k!(n-k)!}$

Combinations refer to the combination of $n$ things taken $k$ at a time without repetition.


# Computing permutations and combinations

Python provides direct methods to find permutations and combinations of a sequence. A Python module which implements a number of iterator building blocks is `itertools` [[doc]](https://docs.python.org/3/library/itertools.html)

`permutations()` returns r-length tuples*, all possible orderings, no repeated elements

`combinations()` returns r-length tuples, in sorted order, no repeated elements

`combinations_with_replacement()` returns r-length tuples, in sorted order, with repeated elements

(*tuples are a data structures that store an ordered sequence of values)


### Permutations

Permutations are typically used in Permutation Test to generate the distribution of a test statistic under the null hypothesis.
For example, if we want to study whether a new drug is effective to treat a pathology, and we have collected data of subjects undergone that treatment and control subjects, the null hypothesis is that the a treatment has no effect.  

This is done by
randomly shuffling the sample many times (i.e. randomly assigning each subject to either the treated or control samples).
Then, the statistic
of interest is computed in each reshuffled sample.

Finally, the estimate from
the original sample is compared with the distribution of estimates from the
reshuffled samples to evaluate how different the observed estimate is from
random reshuffling.

There are different agorithms to generate permutations of a given set. The methods to be applied  depend on whether one wants some randomly chosen permutations, or all permutations.

In [46]:
from itertools import permutations

Get all permutations of [1, 2, 3], with `permutations()`. It generates $n!$ permutations if the length of the input sequence is $n$.

In [47]:
perm = permutations([1, 2, 3])

This method takes a list as an input and returns an object list of tuples that contain all permutations in a list form.

In [48]:
for i in list(perm):
    print (i)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


The same can be done with ['red','blue','green']

We can also get all permutations of a given length, as follows:

In [49]:
perm = permutations([1, 2, 3, 4], 2)
for i in list(perm):
    print (i)

(1, 2)
(1, 3)
(1, 4)
(2, 1)
(2, 3)
(2, 4)
(3, 1)
(3, 2)
(3, 4)
(4, 1)
(4, 2)
(4, 3)


You can count them:

In [50]:
n_perm = 0
perm = permutations([1, 2, 3, 4], 2)
for i in list(perm):
  print(i)
  n_perm += 1

(1, 2)
(1, 3)
(1, 4)
(2, 1)
(2, 3)
(2, 4)
(3, 1)
(3, 2)
(3, 4)
(4, 1)
(4, 2)
(4, 3)


In [51]:
print(f'the number of permutation is {n_perm}')

the number of permutation is 12


In [52]:
type(list(permutations([1, 2, 3, 4], 2)))

list

In [53]:
len(list(permutations([1, 2, 3, 4], 2)))

12

### Combinations

Print all *combinations* of given length

In [54]:
from itertools import combinations

Get all combinations of [1, 2, 3, 4]  and length 2

In [55]:
comb = combinations([1, 2, 3, 4], 2)
for i in list(comb):
    print (i)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


The difference with permutations is apparent. In case of combinations the order is not relevant, thus a smaller number of objects are returned.

 If we want to make a combination of the same element to the same element then we use `combinations_with_replacement()`.

In [56]:
from itertools import combinations_with_replacement

In [57]:
comb = combinations_with_replacement([1, 2, 3, 4], 2)
for i in list(comb):
    print (i)

(1, 1)
(1, 2)
(1, 3)
(1, 4)
(2, 2)
(2, 3)
(2, 4)
(3, 3)
(3, 4)
(4, 4)


### Factorial growth

The number of permutations of $n$ objects is $n!$

The growth of the factorial function with $n$ is very fast. The computation of the factorial can be approximated using the Stirling's formula, which approximates very well the computation for n>30.

In [58]:
7*6*5*4*3*2

5040

In [59]:
import numpy as np

In [60]:
def factorial(n):
    """Computation of the factorial of an integer number n, i.e.: n! = n(n-1)(n-2)...*3*2*1. """
    if n == 0:
        return 1
    else:
        return n*factorial(n-1)

In [61]:
factorial(5)

120

In [62]:
def stirling(n):
    """Stirling's approximation to the factorial."""
    return np.sqrt(2*np.pi*n)*(n/np.e)**n

In [63]:
stirling(5)

118.0191679575901

We can have a look at the fast growing on $n!$

In [123]:
n = np.arange(1, 20, 2)

n_f = [factorial(i) for i in n]

# Assuming you have a stirling function defined or imported
n_nfact = zip(n, n_f, [stirling(i) for i in n])

for i in list(n_nfact):
    print(i)

(1, 1, 0.9221370088957891)
(3, 6, 5.836209591345864)
(5, 120, 118.0191679575901)
(7, 5040, 4980.395831612462)
(9, 362880, 359536.87284194835)
(11, 39916800, 39615625.05057755)
(13, 6227020800, 6187239475.19272)
(15, 1307674368000, 1300430722199.468)
(17, 355687428096000, 353948328666101.1)
(19, 121645100408832000, 1.2111278659229419e+17)


Because the number of permutations grows so fast, it is typically only feasible to use a "Monte Carlo sample" of the possible set of permutations in computation.

## Random permutations

Instead of considering all permutations, it is suitable for many applications to rely only on randomly selected permutations.

The Numpy Random Sampling routine (`numpy.random`) allows to compute random permutations with `numpy.random.permutation` [[doc]](https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html)


In [65]:
import numpy as np

`random.permutation(x)`  randomly permutes a sequence, or returns a permuted range:

In [66]:
my_list =['orange', 'apple', 'pear', 'apricot', 'melon']
np.random.permutation(my_list)

array(['pear', 'apple', 'melon', 'apricot', 'orange'], dtype='<U7')

If you execute the code above several times, you will see that a random permutation is generated at each time.

When given an integer n, permutation treats is as the array arange(n)

In [67]:
np.random.permutation(10)

array([8, 1, 6, 0, 5, 9, 3, 4, 2, 7])

It is possible to permute the indices if you needed to permute collections of arrays in synchrony

We can define two arrays, whose we want to permute the element synchronously:

In [118]:
A = np.arange(12).reshape(6, 2)
B = A + 10

print("Array A:")
print(A)

print("\nArray B (derived by adding 10 to each element of A):")
print(B)

Array A:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

Array B (derived by adding 10 to each element of A):
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]


and permute the indices

In [104]:
print(f"The number of rows is: {A.shape[0]}")

The number of rows is: 6


In [121]:
# Generate a random permutation of indices for the rows of A and B
idx = np.random.permutation(A.shape[0])

# Print the shuffled indices
print(f"Indices: {idx}\n")

# Shuffle the rows of array A based on the generated indices
print(A[idx, :],"\n")

# Print the first column of the shuffled A array
print(f"Printing the first column of A array: {A[idx, 0]}\n")

# Shuffle the rows of array B based on the same indices
print(B[idx, :])

Indices: [5 0 2 3 1 4]

[[10 11]
 [ 0  1]
 [ 4  5]
 [ 6  7]
 [ 2  3]
 [ 8  9]] 

Printing the first column of A array: [10  0  4  6  2  8]

[[20 21]
 [10 11]
 [14 15]
 [16 17]
 [12 13]
 [18 19]]


## Shuffling an array

In [124]:
A = np.random.randint(0, 15, (8, 12))
A

array([[ 6,  1, 14, 13,  3,  8,  6,  0,  8,  5, 12, 12],
       [ 7,  6,  3, 14,  6,  0,  1,  7,  5,  1,  6, 14],
       [ 4,  6,  3, 11, 13,  6,  3, 10, 12, 14,  1,  4],
       [11,  4,  6,  0, 13, 13,  4, 13,  2,  9,  2, 12],
       [ 4, 13, 12,  6, 11, 12,  4,  9,  9, 14,  7,  3],
       [11,  8,  5,  0,  1,  9, 12, 12,  5,  3,  1, 11],
       [ 9, 12,  5,  1,  2,  3, 13,  8,  8,  2,  7,  6],
       [ 0,  3,  9,  0,  5,  1,  1, 14,  7,  9,  3, 13]])

Whereas `np.random.permutation()` creates a copy of an array, in `np.random.shuffle()` the shuffling occurs *in place* for efficiency

In [127]:
np.random.shuffle(A)
A

array([[11,  8,  5,  0,  1,  9, 12, 12,  5,  3,  1, 11],
       [ 6,  1, 14, 13,  3,  8,  6,  0,  8,  5, 12, 12],
       [ 0,  3,  9,  0,  5,  1,  1, 14,  7,  9,  3, 13],
       [ 4,  6,  3, 11, 13,  6,  3, 10, 12, 14,  1,  4],
       [ 9, 12,  5,  1,  2,  3, 13,  8,  8,  2,  7,  6],
       [11,  4,  6,  0, 13, 13,  4, 13,  2,  9,  2, 12],
       [ 4, 13, 12,  6, 11, 12,  4,  9,  9, 14,  7,  3],
       [ 7,  6,  3, 14,  6,  0,  1,  7,  5,  1,  6, 14]])

By default the rows are shuffled. To shuffle columns instead, the transpose array A.T should be shuffled.

In [77]:
A.T

array([[7, 3, 6, 9, 2, 3, 7, 7],
       [8, 8, 5, 8, 8, 1, 7, 8],
       [6, 4, 0, 4, 7, 5, 7, 0],
       [0, 2, 7, 6, 2, 8, 8, 4],
       [6, 8, 7, 2, 2, 3, 3, 6],
       [0, 5, 8, 1, 9, 2, 0, 1],
       [6, 2, 8, 9, 9, 7, 3, 0],
       [3, 3, 1, 1, 8, 3, 4, 6],
       [1, 3, 8, 0, 6, 5, 9, 0],
       [3, 1, 3, 5, 9, 4, 3, 6],
       [4, 5, 2, 0, 7, 2, 9, 2],
       [1, 4, 3, 5, 8, 5, 0, 2]])

We can shuffle an array also with the `sklearn.utils.shuffle`

`sklearn.utils.shuffle(*arrays, random_state=None, n_samples=None)`

It can consistenly shuffle different kinds of arrays.

In [80]:
X_features = np.array([[1., 2.1], [2., 3.1], [2.5, 3.], [0.5, 1.8], [0.7, 1.5], [1.5, 3.8], [0.7, 1.5], [0.3, 1.2]])
Y_diagnosis = [1, 0, 1, 0, 1, 0, 1, 1]

In [81]:
X_features, Y_diagnosis

(array([[1. , 2.1],
        [2. , 3.1],
        [2.5, 3. ],
        [0.5, 1.8],
        [0.7, 1.5],
        [1.5, 3.8],
        [0.7, 1.5],
        [0.3, 1.2]]),
 [1, 0, 1, 0, 1, 0, 1, 1])

In [136]:
from sklearn.utils import shuffle

In [176]:
sX_features, sY_diagnosis = shuffle(X_features, Y_diagnosis,  random_state=1323)

In [177]:
sX_features, sY_diagnosis

(array([[0.7, 1.5],
        [0.7, 1.5],
        [0.5, 1.8],
        [1.5, 3.8],
        [1. , 2.1],
        [2.5, 3. ],
        [2. , 3.1],
        [0.3, 1.2]]),
 [1, 1, 0, 0, 1, 1, 0, 1])